### ISSUE TITLE
KeyError: 'corsets & bodysuits'

### ISSUE THREAD

**Issue by Null-0000** [hssip/FashionSAP#5]
您好，新更新的代码在做subcategory recognition的验证的时候，会报错KeyError: 'corsets & bodysuits'
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/fashionsap/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/fashionsap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/fashionsap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/wang_ke_jie/FashionSAP/dataset/fashiongen_dataset_catereg.py", line 142, in __getitem__
    label = self.__get_label(cap_index)
  File "/wang_ke_jie/FashionSAP/dataset/fashiongen_dataset_catereg.py", line 124, in __get_label
    label = torch.tensor([self.label_map[cate]], dtype=torch.long)
KeyError: 'corsets & bodysuits'

**Comment by hssip** [comment]
The bug has been fixed in [commit](https://github.com/hssip/FashionSAP/commit/22be3c2a1006211bf119dad9df5b6ee91fc9bfef). Thanks for your suggestion.
